### DISCUSSION TITLE
Altimeter data

### DISCUSSION THREAD

**Discussion by mackenziemeier86** [c-proof/pyglider#199] [Q&A]
Is there an way to add altimeter data to the netcdf files? 

I would assume including "m_water_depth" in the deploymentrealtime.ymal would work, but what parameters does it need?

Starting with this and wondering what else I need to include - or if it should be formatted differently?
  water_depth:
    source:  m_water_depth
    long_name:    altimeter depth
    standard_name: water_depth
    units:        m
    coordinates:  time depth latitude longitude

Thanks for the help!

**Comment by jklymak** [comment]
I've moved to the discussion forum rather than an issue.

All pyglider cares about is "source".  After that the information is just whatever you want in the attributes of the variable.  So if you want 

```
raw_altitude:
    source:  m_raw_altitude
    long_name: whatever the heck you want
    units: whatever you think the units are. 
    ...
```
